up:
  - go: auto
  - github-release:
      golangci/golangci-lint: 1.60.1

path:
  append__toappend:
    - example
    - example-dist

commands:
  test:
    desc: Run all tests
    run: |
      set -e
      omni test lint
      omni test unit
    subcommands:
      lint:
        desc: Run lint
        run: golangci-lint run
      unit:
        desc: Run unit and integration tests
        run: go test ./...

  build:
    desc: Build omni-metagen-go
    run: |
      go build -o dist/omni-metagen-go ./cmd/omni-metagen-go
    subcommands:
      example:
        desc: Build the example
        run: |
          go generate ./example/...
          go build -o example-dist/sdkgoexample2 ./example
